apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluentd-service-account
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: fluentd-service-account
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
